# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'EmployeeManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for EmployeeManagement
	pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
	pod 'Firebase/Storage'
	pod 'SnapKit', '~> 5.6.0'
	pod 'FSCalendar'
end
